export enum RedisCacheKeys {
  GET_USER = 'GET_USER',
  LIST_USERS = 'LIST_USERS',
  AUTH_PASS = 'AUTH_PASS',
  LIMIT_REQUESTS = 'LIMIT_REQUESTS',
  GET_PROPERTY = 'GET_PROPERTY',
  LIST_PROPERTIES = 'LIST_PROPERTIES',
  GET_RENT = 'GET_RENT',
  LIST_RENTS = 'LIST_RENTS',
  GET_TRANSACTION = 'GET_TRANSACTION',
  LIST_TRANSACTIONS = 'LIST_TRANSACTIONS'
}
