export enum RedisCacheKeys {
  GET_USER = 'GET_USER',
  LIST_USERS = 'LIST_USERS',
  AUTH_PASS = 'AUTH_PASS',
  LIMIT_REQUESTS = 'LIMIT_REQUESTS',
  GET_TASK = 'GET_TASK',
  LIST_TASKS = 'LIST_TASKS',
  GET_RESPONSE = 'GET_RESPONSE',
  LIST_RESPONSES = 'LIST_RESPONSES'
}
